export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST';
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS';

export const POST_INIFINITE_REQUEST = 'POST_INIFINITE_REQUEST';
export const POST_INIFINITE_SUCCESS = 'POST_INIFINITE_SUCCESS';
export const POST_INIFINITE_NOMORE = 'POST_INIFINITE_NOMORE';

export const POST_PAGINATE_REQUEST_NEXT = 'POST_PAGINATE_REQUEST_NEXT';
export const POST_PAGINATE_REQUEST_PREV = 'POST_PAGINATE_REQUEST_PREV';
export const POST_PAGINATE_NEXT_SUCCESS = 'POST_PAGINATE_NEXT_SUCCESS';
export const POST_PAGINATE_PREV_SUCCESS = 'POST_PAGINATE_PREV_SUCCESS';
export const POST_PAGINATE_NEXT_NOMORE = 'POST_PAGINATE_NOMORE';
export const POST_PAGINATE_PREV_NOMORE = 'POST_PAGINATE_NOMORE';

export const POST_ADD_REQUEST = 'POST_ADD_REQUEST';
export const POST_ADD_SUCCESS = 'POST_ADD_SUCCESS';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';

export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST';
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS';

export const POST_FAIL = 'POST_FAIL';
